import {NextResponse} from "next/server";
import {currentAdmin} from "@/lib/auth";
import {database} from "@/lib/database";
import {sameOrigin} from "@/lib/security";
const allowed=new Set(["bio","role","github_url","linkedin_url","seo_title","seo_description","privacy_retention_days","theme_default"]);
function bad(message:string,status:number){return NextResponse.json({error:message},{status,headers:{"Cache-Control":"no-store"}})}
function isValid(key:string,value:unknown){if(key==="privacy_retention_days")return Number.isInteger(value)&&Number(value)>=1&&Number(value)<=365;if(key==="theme_default")return value==="light"||value==="dark";if(typeof value!=="string"||value.length>6000)return false;if(key.endsWith("_url")){try{return new URL(value).protocol==="https:"}catch{return false}}return true}
export async function PATCH(request:Request,context:RouteContext<"/api/admin/settings/[key]">){if(!sameOrigin(request))return bad("This request could not be accepted.",403);const {key}=await context.params;if(!allowed.has(key))return bad("Not found.",404);if(!await currentAdmin())return bad("Authentication required.",401);try{const body=await request.json() as {value?:unknown};if(!isValid(key,body.value))return bad("Check the setting and try again.",400);const {rows}=await database().query("INSERT INTO portfolio_settings(key,value) VALUES($1,$2::jsonb) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now() RETURNING key,value,updated_at",[key,JSON.stringify(body.value)]);return NextResponse.json({item:rows[0]},{headers:{"Cache-Control":"no-store"}})}catch{return bad("Could not save the setting.",400)}}
export async function DELETE(request:Request,context:RouteContext<"/api/admin/settings/[key]">){if(!sameOrigin(request))return bad("This request could not be accepted.",403);const {key}=await context.params;if(!allowed.has(key))return bad("Not found.",404);if(!await currentAdmin())return bad("Authentication required.",401);try{const body=await request.json() as {confirm?:unknown};if(body.confirm!==true)return bad("Explicit confirmation is required.",400);const {rowCount}=await database().query("DELETE FROM portfolio_settings WHERE key=$1",[key]);return rowCount?new NextResponse(null,{status:204}):bad("Setting not found.",404)}catch{return bad("Could not delete the setting.",400)}}

