import type { Metadata } from "next";
import Link from "next/link";
import { getPublicProfileRecords, getPublicSettings } from "@/lib/profile";
import { getActiveResume } from "@/lib/resumes";
import Reveal from "@/components/reveal";
export const metadata: Metadata = { title: "About", description: "About Arshan Ashraf and his full-stack application development practice." };
const focusAreas = ["Frontend", "Backend & APIs", "Databases", "Real-time & distributed systems", "DevOps & tooling", "AI applications", "Application development"];
const directions = ["Node path", "Layered system", "Connected modules"];
const confidenceLabel = { core: "Core", working_knowledge: "Working knowledge", currently_learning: "Currently learning", exploring: "Exploring" };
export default async function AboutPage() {
  const [{ skills, experience, achievements }, settings, resume] = await Promise.all([getPublicProfileRecords(), getPublicSettings(["bio", "role", "github_url", "linkedin_url"]), getActiveResume()]);
  const bio = typeof settings.bio === "string" ? settings.bio : "My interests span user-facing interfaces, APIs, databases, real-time and event-driven systems, and AI application development. I’m continuing to expand my practice in Next.js, application development, AI engineering, and modern software architecture.";
  const role = typeof settings.role === "string" ? settings.role : "Full-Stack Developer";
  return <main className="page-main shell about-page"><div className="page-intro"><span className="section-kicker">01 / PROFILE · ARSHAN ASHRAF</span><h1>Interested in how<br/>the pieces <span>fit.</span></h1><p>{role}: I build modern web applications across frontend, backend, and AI-enabled experiences.</p>{resume && <a className="evidence-link" href="/api/resume?download=1" download>Download résumé ↓</a>}</div>
    <Reveal as="section" className="content-block"><span className="section-kicker">02 / FOCUS</span><h2>Connected systems, considered experiences.</h2><p>{bio}</p><p>Each technology is a tool, not a trophy. Project write-ups focus on the choices, trade-offs, and evidence behind the work.</p><div className="focus-tags">{focusAreas.map((area) => <span key={area}>{area}</span>)}</div></Reveal>
    <Reveal as="section" className="content-block" id="skills"><span className="section-kicker">03 / STACK</span><h2>Skills and confidence.</h2>{skills.length ? <div className="skill-list">{skills.map((skill) => <article className="skill-row" key={skill.id}><span>{skill.group_name}</span><b>{skill.name}</b><span className="skill-level">{confidenceLabel[skill.confidence]}</span>{skill.description && <p>{skill.description}</p>}</article>)}</div> : <p className="editorial-note">No skill levels are published yet. Each item and confidence label will be set by the owner.</p>}</Reveal>
    <Reveal as="section" className="content-block" id="experience"><span className="section-kicker">04 / EXPERIENCE</span><h2>Context for the work.</h2>{experience.length ? <div className="timeline">{experience.map((item) => <Reveal as="article" className="timeline-item" key={item.id}><span>{item.started_on ? new Date(item.started_on).getUTCFullYear() : ""}{item.ended_on ? " — " + new Date(item.ended_on).getUTCFullYear() : item.started_on ? " — Present" : ""}</span><div><h3>{item.role} · {item.organization}</h3><p>{item.description}</p></div></Reveal>)}</div> : <p className="editorial-note">Verified experience details will appear here when provided.</p>}</Reveal>
    <Reveal as="section" className="content-block" id="achievements"><span className="section-kicker">05 / ACHIEVEMENTS</span><h2>Milestones, with evidence.</h2>{achievements.length ? <div className="achievement-grid">{achievements.map((item, index) => <article className="achievement-card" key={item.id}><span className="section-kicker">{String(index + 1).padStart(2, "0")} / MILESTONE{item.achieved_on ? ` · ${new Date(item.achieved_on).getUTCFullYear()}` : ""}</span><h3>{item.title}</h3><p>{item.description}</p>{item.evidence_url && <a className="evidence-link" href={item.evidence_url} target="_blank" rel="noreferrer">Supporting evidence ↗</a>}</article>)}</div> : <p className="editorial-note">No achievements have been published.</p>}</Reveal>
    <Reveal as="section" className="content-block"><span className="section-kicker">06 / IDENTITY</span><h2>Three directions for the system mark.</h2><p>These early sketches are for owner review. The header mark is a temporary direction; no final logo has been selected.</p><div className="logo-directions">{directions.map((direction, index) => <article className="logo-direction" key={direction}><span className="direction-number">0{index + 1} / EXPLORATION</span><div className={`direction-mark direction-mark--${index + 1}`} aria-hidden="true"><i/><i/><i/></div><h3>{direction}</h3><p>Arshan Ashraf</p></article>)}</div></Reveal>
    <Reveal as="section" className="content-block profile-links"><span className="section-kicker">07 / IDENTITY ONLINE</span><a href={typeof settings.github_url === "string" ? settings.github_url : "https://github.com/Arshanashraf"} target="_blank" rel="noreferrer">GitHub — Arshanashraf <span>↗</span></a><a href={typeof settings.linkedin_url === "string" ? settings.linkedin_url : "https://linkedin.com/in/arshan-ashraf-650124288/"} target="_blank" rel="noreferrer">LinkedIn — Arshan Ashraf <span>↗</span></a><Link href="/projects">Browse project index <span>↗</span></Link></Reveal>
  </main>;
}

