import Link from "next/link";
import { getPublicProjects } from "@/lib/projects";
import { getPublicProfileRecords } from "@/lib/profile";
import { getPublishedArticles } from "@/lib/articles";
import { getActiveResume } from "@/lib/resumes";
import SkillAtlas from "@/components/skill-atlas";
import ProjectShowcase from "@/components/project-showcase";
import Reveal from "@/components/reveal";
import MotionDirector from "@/components/motion-director";
function SystemMap() { return <svg className="system-map" viewBox="0 0 560 410" fill="none" role="img" aria-labelledby="map-title map-desc"><title id="map-title">Interactive map of an application stack</title><desc id="map-desc">Interface connects to application services, intelligence, data, and operations with feedback between layers. Focus or hover a node to highlight it.</desc><path className="map-path" d="M123 84h110v102m0-102h201v102M233 186v100m0-100h201v100M123 286h110m0 0h201"/><path className="map-path map-path--dash" d="M434 186V84H233m0 102H123v100"/><g className="map-node map-node--accent" tabIndex={0}><rect x="54" y="49" width="138" height="70" rx="5"/><circle cx="76" cy="72" r="7"/><text x="92" y="75">INTERFACE</text><text className="map-sub" x="76" y="98">React · Next.js</text></g><g className="map-node" tabIndex={0}><rect x="164" y="151" width="138" height="70" rx="5"/><circle cx="186" cy="174" r="7"/><text x="202" y="177">APPLICATION</text><text className="map-sub" x="186" y="200">APIs · services</text></g><g className="map-node" tabIndex={0}><rect x="365" y="151" width="138" height="70" rx="5"/><circle cx="387" cy="174" r="7"/><text x="403" y="177">INTELLIGENCE</text><text className="map-sub" x="387" y="200">Retrieval · models</text></g><g className="map-node" tabIndex={0}><rect x="164" y="251" width="138" height="70" rx="5"/><circle cx="186" cy="274" r="7"/><text x="202" y="277">DATA</text><text className="map-sub" x="186" y="300">Storage · events</text></g><g className="map-node map-node--muted" tabIndex={0}><rect x="365" y="251" width="138" height="70" rx="5"/><circle cx="387" cy="274" r="7"/><text x="403" y="277">OPERATIONS</text><text className="map-sub" x="387" y="300">Containers · tools</text></g><text className="map-annotation" x="54" y="366">A SYSTEM IS A SET OF CONNECTIONS.</text><text className="map-annotation" x="430" y="366">FIG. 01 / STACK</text></svg>; }
export default async function Home() {
  const [projects, profile, articles, resume] = await Promise.all([getPublicProjects(), getPublicProfileRecords(), getPublishedArticles(), getActiveResume()]);
  const selected = projects.slice(0, 6); const activeProject = projects.find((project) => project.currentlyBuilding && !project.placeholder);
  return <main id="top"><MotionDirector/><section className="hero shell"><div className="hero-copy"><div className="eyebrow hero-enter hero-enter--1"><span className="status-dot"/> DEVELOPER / SOFTWARE ENGINEER <span className="eyebrow-meta">ARSHANASHRAF</span></div><p className="hero-name hero-enter hero-enter--2">ARSHAN ASHRAF</p><h1 className="hero-enter hero-enter--2">I build modern<br/>web applications<br/><span>across the stack.</span></h1><p className="hero-lede hero-enter hero-enter--3">Across frontend, backend, and AI-enabled experiences. I’m interested in how thoughtful systems connect into products people can use.</p><div className="hero-actions hero-enter hero-enter--4"><Link className="button button--primary" href="/projects">View projects <span>↗</span></Link>{resume ? <a className="button button--quiet resume-download" href="/api/resume?download=1" download>Download résumé <span>↓</span></a> : <Link className="button button--quiet resume-unavailable" href="/contact" aria-label="Résumé currently unavailable. Contact Arshan.">Résumé currently unavailable <span>↗</span></Link>}</div><div className="hero-socials hero-enter hero-enter--4"><Link href="/about">About Arshan ↗</Link><Link href="/contact">Contact ↗</Link></div></div><div className="hero-visual hero-enter hero-enter--5"><div className="visual-label"><span>APPLICATION MAP</span><span>001—026</span></div><SystemMap/><div className="visual-label visual-label--bottom"><span>DESIGN · LOGIC · SYSTEMS</span><span>FIG 01</span></div></div><a className="scroll-cue" href="#selected-work"><span/>Scroll to explore</a></section>
  <section className="intro-band" data-motion-reveal="statement"><div className="shell intro-band-inner"><span className="section-kicker">01 / SYSTEM</span><p>Good software is more than a set of features. It’s a thoughtful system—<span>clear to use, sound underneath, and built to work together.</span></p><span className="intro-band-mark" aria-hidden="true">⟡</span></div></section>
  <section className="section shell skills-section" id="stack" data-motion-reveal="section"><div className="section-heading"><div><span className="section-kicker">02 / STACK</span><h2>Technology, in context<span className="accent-dot">.</span></h2></div><Link className="text-link" href="/about#skills">Explore profile ↗</Link></div><SkillAtlas skills={profile.skills}/></section>
  <section className="section shell project-section" id="selected-work" data-motion-reveal="projects"><div className="section-heading"><div><span className="section-kicker">03 / WORK</span><h2>Selected systems<span className="accent-dot">.</span></h2></div><Link className="text-link" href="/projects">Project index ↗</Link></div>{selected.some((project) => project.placeholder) && <p className="sample-notice"><span>!</span> Sample project records are visible for local review; replace with verified details before publishing.</p>}<ProjectShowcase projects={selected}/></section>
  {activeProject && <section className="currently-building" data-motion-reveal="statement"><div className="shell currently-building-inner"><div><span className="section-kicker">04 / CURRENTLY BUILDING</span><h2>{activeProject.title}</h2><p>{activeProject.summary}</p><Link className="text-link" href={`/projects/${activeProject.slug}`}>Explore current project ↗</Link></div><span className="active-status"><i/> ACTIVE PROJECT · OWNER MARKED</span></div></section>}
  {profile.experience.length > 0 && <section className="section shell home-timeline" data-motion-reveal="section"><div className="section-heading"><div><span className="section-kicker">05 / EXPERIENCE</span><h2>Work, over time<span className="accent-dot">.</span></h2></div><Link className="text-link" href="/about#experience">Full profile ↗</Link></div><div className="timeline">{profile.experience.slice(0, 3).map((item) => <Reveal as="article" className="timeline-item" key={item.id}><span>{item.started_on ? new Date(item.started_on).getUTCFullYear() : ""}{item.ended_on ? " — " + new Date(item.ended_on).getUTCFullYear() : item.started_on ? " — Present" : ""}</span><div><h3>{item.role} · {item.organization}</h3><p>{item.description}</p></div></Reveal>)}</div></section>}
  {profile.achievements.length > 0 && <section className="section shell home-achievements" data-motion-reveal="section"><div className="section-heading"><div><span className="section-kicker">06 / MILESTONES</span><h2>Evidence over claims<span className="accent-dot">.</span></h2></div><Link className="text-link" href="/about#achievements">All milestones ↗</Link></div><div className="achievement-grid">{profile.achievements.slice(0, 3).map((item, index) => <Reveal as="article" className="achievement-card" key={item.id}><span className="section-kicker">{String(index + 1).padStart(2, "0")} / ACHIEVEMENT</span><h3>{item.title}</h3><p>{item.description}</p>{item.evidence_url && <a className="text-link" href={item.evidence_url} target="_blank" rel="noreferrer">Evidence ↗</a>}</Reveal>)}</div></section>}
  {articles.length > 0 && <section className="section shell home-writing" data-motion-reveal="section"><div className="section-heading"><div><span className="section-kicker">07 / NOTES</span><h2>Writing &amp; ideas<span className="accent-dot">.</span></h2></div><Link className="text-link" href="/writing">All writing ↗</Link></div><div className="article-list">{articles.slice(0, 2).map((article, index) => <Reveal as="article" className="article-card" key={article.slug}><Link href={`/writing/${article.slug}`}><span className="section-kicker">{String(index + 1).padStart(2, "0")} / {article.category || "ARTICLE"} · {new Date(article.published_at).toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" })}</span><h3>{article.title}</h3><p>{article.excerpt}</p><span className="article-more">Read article ↗</span></Link></Reveal>)}</div></section>}
  <section className="contact-strip shell" data-motion-reveal="contact"><div><span className="section-kicker">08 / CONTACT</span><h2>Have a system to build?</h2></div><div className="contact-strip-actions"><Link className="button button--primary" href="/contact">Start a conversation ↗</Link>{resume && <a className="text-link" href="/api/resume?download=1" download>Download résumé ↓</a>}</div></section></main>;
}

