"use client";
import Link from "next/link";
import { useRef, useState, type PointerEvent, type KeyboardEvent } from "react";
import type { Project } from "@/data/projects";
function ProjectMap({ title, index }: { title: string; index: number }) { return <div className="project-map" aria-label={`Abstract systems map for ${title}`}><span className="project-map-coordinate">SYS / {String(index + 1).padStart(2, "0")}</span><svg viewBox="0 0 600 330" role="img" aria-hidden="true"><path d="M100 90h170v75m0-75h220m-220 75v90m0-90h220v90M100 255h170m0 0h220"/><path className="project-map-flow" d="M100 90h170v75h220v90"/><g><rect x="38" y="61" width="125" height="58"/><text x="58" y="88">INTERFACE</text><circle cx="51" cy="78" r="4"/></g><g><rect x="208" y="136" width="125" height="58"/><text x="228" y="163">APPLICATION</text><circle cx="221" cy="153" r="4"/></g><g><rect x="428" y="61" width="125" height="58"/><text x="448" y="88">SERVICES</text><circle cx="441" cy="78" r="4"/></g><g><rect x="428" y="226" width="125" height="58"/><text x="448" y="253">DATA</text><circle cx="441" cy="243" r="4"/></g><text className="project-map-name" x="38" y="310">{title.toUpperCase()}</text></svg><span className="project-map-caption">SYSTEM STUDY · NO PROJECT SCREENSHOTS SUPPLIED</span></div>; }
export default function ProjectShowcase({ projects }: { projects: Project[] }) {
  const [index, setIndex] = useState(0); const pointer = useRef<number | null>(null); const startX = useRef(0);
  if (!projects.length) return <div className="empty-state"><h3>Project index in progress.</h3><p>Published projects will appear here when verified and released.</p></div>;
  const project = projects[index];
  function move(direction: number) { setIndex((current) => (current + direction + projects.length) % projects.length); }
  function keyMove(event: KeyboardEvent<HTMLElement>) { if (event.key === "ArrowLeft") { event.preventDefault(); move(-1); } if (event.key === "ArrowRight") { event.preventDefault(); move(1); } }
  function pointerDown(event: PointerEvent<HTMLElement>) { if ((event.target as HTMLElement).closest("button, a")) return; pointer.current = event.pointerId; startX.current = event.clientX; event.currentTarget.setPointerCapture(event.pointerId); }
  function pointerUp(event: PointerEvent<HTMLElement>) { if (pointer.current !== event.pointerId) return; const distance = event.clientX - startX.current; if (Math.abs(distance) > 45) move(distance < 0 ? 1 : -1); pointer.current = null; }
  return <div className="project-showcase" onKeyDown={keyMove} onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={() => { pointer.current = null; }} tabIndex={0} aria-label="Project showcase. Use arrow keys to change projects."><div className="showcase-visual" key={project.slug}><ProjectMap title={project.title} index={index}/><span className="showcase-sample">{project.placeholder ? "SAMPLE CONTENT" : "PROJECT SYSTEM"}</span></div><div className="showcase-details" key={`${project.slug}-details`}><div className="showcase-heading"><span className="section-kicker">PROJECT {String(index + 1).padStart(2, "0")} / {String(projects.length).padStart(2, "0")}</span><span className="project-category">{project.category}</span></div><h3>{project.title}</h3><p>{project.summary}</p><div className="showcase-tech">{project.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div>{project.placeholder && <p className="editorial-note">Sample content — replace with verified project details.</p>}<div className="showcase-actions"><Link className="button button--primary" href={`/projects/${project.slug}`}>View case study <span>↗</span></Link>{project.repoUrl && <a className="text-link" href={project.repoUrl} target="_blank" rel="noreferrer">GitHub ↗</a>}{project.demoUrl && <a className="text-link" href={project.demoUrl} target="_blank" rel="noreferrer">Live demo ↗</a>}</div></div><div className="showcase-controls"><button type="button" aria-label="Previous project" onClick={() => move(-1)}>←</button><div className="showcase-progress" role="group" aria-label="Choose project">{projects.map((item, itemIndex) => <button type="button" key={item.slug} aria-label={`Show project ${itemIndex + 1}: ${item.title}`} aria-current={itemIndex === index ? "true" : undefined} onClick={() => setIndex(itemIndex)}><i/></button>)}</div><button type="button" aria-label="Next project" onClick={() => move(1)}>→</button></div></div>;
}

