"use client";
import { useCallback, useEffect, useState } from "react";
import type { AdminField } from "@/data/admin-resources";
type Resource = "projects"|"skills"|"experience"|"achievements"|"blog-posts"|"messages";
type RecordValue=Record<string,unknown>;
type Props={resource:Resource;title:string;fields:AdminField[]};
function blank(fields:AdminField[]):RecordValue{return Object.fromEntries(fields.map((field)=>[field.name,field.kind==="checkbox"?false:field.kind==="number"?0:field.kind==="select"?(field.options?.[0]?.value??""): ""]));}

export default function ResourceManager({resource,title,fields}:Props){const [items,setItems]=useState<RecordValue[]>([]);const [form,setForm]=useState<RecordValue>(()=>blank(fields));const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [detail,setDetail]=useState<RecordValue|null>(null);const [showPreview,setShowPreview]=useState(false);
const refresh=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/"+resource,{cache:"no-store"});const body=await response.json() as {items?:RecordValue[];error?:string};if(!response.ok)throw new Error(body.error||"Could not load records.");setItems(body.items??[]);}catch(problem){setError(problem instanceof Error?problem.message:"Could not load records.");}finally{setLoading(false);}},[resource]);
useEffect(()=>{let active=true;fetch("/api/admin/"+resource,{cache:"no-store"}).then(async(response)=>{const body=await response.json() as {items?:RecordValue[];error?:string};if(!response.ok)throw new Error(body.error||"Could not load records.");if(active)setItems(body.items??[])}).catch((problem)=>{if(active)setError(problem instanceof Error?problem.message:"Could not load records.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[resource]);
function startNew(){setEditing(null);setForm(blank(fields));setError("");setNotice("");}
function startEdit(item:RecordValue){setEditing(String(item.id));setForm(Object.fromEntries(fields.map((field)=>{let value=item[field.name];if(field.kind==="date"&&value instanceof Date)value=value.toISOString().slice(0,10);else if(field.kind==="date"&&typeof value==="string")value=value.slice(0,10);if(value===null||value===undefined)value=field.kind==="checkbox"?false:field.kind==="number"?0:"";return[field.name,value]})));setError("");setNotice("");window.scrollTo({top:0,behavior:"smooth"});}
async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setNotice("");const payload=Object.fromEntries(fields.map((field)=>{const value=form[field.name];return[field.name,field.kind==="number"?Number(value):field.kind==="checkbox"?Boolean(value):field.kind==="date"&&value===""?null:value===""?"":value]}));try{const response=await fetch(editing?"/api/admin/"+resource+"/"+editing:"/api/admin/"+resource,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Could not save changes.");setNotice("Saved.");startNew();await refresh();}catch(problem){setError(problem instanceof Error?problem.message:"Could not save changes.");}finally{setBusy(false);}}
async function remove(item:RecordValue){if(!window.confirm("Delete this record permanently? This cannot be undone."))return;setError("");try{const response=await fetch("/api/admin/"+resource+"/"+item.id,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirm:true})});if(!response.ok)throw new Error("Could not delete this record.");if(editing===item.id)startNew();await refresh();setNotice("Record deleted.");}catch(problem){setError(problem instanceof Error?problem.message:"Could not delete this record.");}}
async function setMessageStatus(item:RecordValue,status:"read"|"archived"){const response=await fetch("/api/admin/messages/"+item.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!response.ok){setError("Could not update the message.");return}await refresh();setDetail({...item,status});}
return <div className="manager-layout"><section className="manager-main"><div className="manager-title"><div><span className="section-kicker">CONTENT MANAGEMENT</span><h1>{title}</h1></div>{resource!=="messages"&&<button type="button" className="button button--primary" onClick={startNew}>+ New record</button>}</div>{resource==="projects"&&<p className="admin-note">Project samples begin as drafts. Confirm each record’s sample label and facts before publishing.</p>}{notice&&<p className="admin-success" role="status">{notice}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}
{resource!=="messages"&&<form className="editor-form" onSubmit={save}><div className="form-heading"><div><span className="section-kicker">{editing?"EDIT RECORD":"NEW RECORD"}</span><h2>{editing?"Update details":"Add to "+title.toLowerCase()}</h2></div><button type="button" className="text-button" onClick={()=>setShowPreview(!showPreview)}>{showPreview?"Hide preview":"Preview"}</button>{editing&&<button type="button" className="text-button" onClick={startNew}>Cancel</button>}</div><div className="admin-fields">{fields.map((field)=>{const id="field-"+field.name;return <label className={"admin-field "+(field.kind==="textarea"?"admin-field--wide":"")} key={field.name} htmlFor={id}><span>{field.label}{field.required&&<b> *</b>}</span>{field.kind==="textarea"?<textarea id={id} value={String(form[field.name]??"")} maxLength={12000} required={field.required} onChange={(event)=>setForm({...form,[field.name]:event.target.value})}/>:field.kind==="select"?<select id={id} value={String(form[field.name]??"")} required={field.required} onChange={(event)=>setForm({...form,[field.name]:event.target.value})}>{field.options?.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.kind==="checkbox"?<input id={id} type="checkbox" checked={Boolean(form[field.name])} onChange={(event)=>setForm({...form,[field.name]:event.target.checked})}/>:<input id={id} type={field.kind} value={String(form[field.name]??"")} required={field.required} min={field.kind==="number"?0:undefined} onChange={(event)=>setForm({...form,[field.name]:field.kind==="number"?(event.target.value===""?0:Number(event.target.value)):event.target.value})}/>}{field.help&&<small>{field.help}</small>}</label>})}</div><button className="button button--primary" type="submit" disabled={busy}>{busy?"Saving…":editing?"Save changes":"Create draft"}</button>{showPreview&&(resource==="projects"||resource==="blog-posts")&&<section className="draft-preview"><span className="section-kicker">PRIVATE EDITOR PREVIEW · NOT PUBLIC</span><h3>{String(form.title||"Untitled draft")}</h3><p>{String(form.summary||form.excerpt||"")}</p><pre>{String(form.body_markdown||form.approach||form.context||"")}</pre></section>}</form>}
<section className="record-list"><div className="form-heading"><div><span className="section-kicker">SAVED CONTENT</span><h2>{loading?"Loading…":items.length+" records"}</h2></div></div>{loading?<p className="admin-muted">Fetching records…</p>:items.length===0?<div className="admin-empty"><h3>Nothing here yet.</h3><p>Records you create will appear in this list.</p></div>:items.map((item)=>{const identifier=String(item.id);const label=String(item.title??item.name??item.organization??item.sender_name??"Setting");const subtitle=resource==="messages"?String(item.sender_email??""):String(item.status??item.group_name??item.role??item.category??"");return <article className="record-card" key={identifier}><button className="record-select" type="button" onClick={()=>resource==="messages"?setDetail(detail?.id===item.id?null:item):startEdit(item)}><span><b>{label}</b><small>{subtitle} · {resource==="messages"?new Date(String(item.received_at)).toLocaleDateString():String(item.slug??item.confidence??"")}</small></span><span className="record-chevron">{resource==="messages"?(detail?.id===item.id?"−":"+"):"Edit ↗"}</span></button>{resource==="messages"&&detail?.id===item.id&&<div className="message-detail"><p>{String(item.body??"")}</p><div><button type="button" className="text-button" onClick={()=>void setMessageStatus(item,"read")}>Mark read</button><button type="button" className="text-button" onClick={()=>void setMessageStatus(item,"archived")}>Archive</button><button type="button" className="text-button text-button--danger" onClick={()=>void remove(item)}>Delete</button></div></div>}{resource==="projects"&&Boolean(item.is_sample)&&<span className="sample-pill">SAMPLE CONTENT</span>}</article>})}</section></section><aside className="manager-aside"><span className="section-kicker">PUBLISHING NOTES</span><p>Changes save directly to PostgreSQL. Public pages show published records only.</p><p>Drafts remain private. Sample records are labeled and no measured results are inferred.</p><p>Media uploads are deferred; add optimized static media links where supported.</p></aside></div>;
}

