"use client";
import { useEffect, useState } from "react";
type Resume = { id: string; file_name: string; version: number; is_active: boolean; file_available: boolean; uploaded_at: string; updated_at: string };
export default function ResumeManager() {
  const [items, setItems] = useState<Resume[]>([]); const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function refresh() { const response = await fetch("/api/admin/resumes", { cache: "no-store" }); const body = await response.json() as { items?: Resume[]; error?: string }; if (!response.ok) throw new Error(body.error || "Could not load resume versions."); setItems(body.items ?? []); }
  useEffect(() => { let active = true; fetch("/api/admin/resumes", { cache: "no-store" }).then(async (response) => { const body = await response.json() as { items?: Resume[]; error?: string }; if (!response.ok) throw new Error(body.error || "Could not load resume versions."); if (active) setItems(body.items ?? []); }).catch((problem) => { if (active) setError(problem instanceof Error ? problem.message : "Could not load resume versions."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!file) { setError("Choose a PDF file first."); return; } setBusy(true); setError(""); setNotice(""); try { const data = new FormData(); data.set("resume", file); const response = await fetch("/api/admin/resumes", { method: "POST", body: data }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "Upload failed."); setFile(null); form.reset(); setNotice("Resume uploaded and activated."); await refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Upload failed."); } finally { setBusy(false); } }
  async function setActive(item: Resume, active: boolean) { setBusy(true); setError(""); try { const response = await fetch(`/api/admin/resumes/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(active ? { activate: true } : { deactivate: true }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "Could not update the active version."); setNotice(active ? `Version ${item.version} is now active.` : `Version ${item.version} has been deactivated.`); await refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not update the active version."); } finally { setBusy(false); } }
  async function remove(item: Resume) { if (!window.confirm(`Delete resume version ${item.version} (${item.file_name})?`)) return; setBusy(true); try { const response = await fetch(`/api/admin/resumes/${item.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirm: true }) }); const body = response.status === 204 ? {} : await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "Could not delete this version."); setNotice(`Version ${item.version} deleted.`); await refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not delete this version."); } finally { setBusy(false); } }
  return <main className="resume-manager"><div className="manager-title"><div><span className="section-kicker">PROFILE DOCUMENTS</span><h1>Résumé versions</h1></div>{items.some((item) => item.is_active && item.file_available) && <a className="button button--quiet" href="/api/resume" target="_blank" rel="noreferrer">View active PDF ↗</a>}</div><p className="admin-note">Upload an owner-approved PDF. A new upload activates as the current version; previous versions remain available here until deleted.</p>{notice && <p className="admin-success" role="status">{notice}</p>}{error && <p className="admin-error" role="alert">{error}</p>}<form className="resume-upload" onSubmit={upload}><label className="admin-field"><span>Choose PDF · max 8 MB</span><input type="file" accept="application/pdf,.pdf" required onChange={(event) => setFile(event.target.files?.[0] ?? null)}/></label><p className="editorial-note">Files are saved under private server storage. This local storage must be backed by a persistent disk on deployment.</p><button type="submit" className="button button--primary" disabled={busy || !file}>{busy ? "Please wait…" : "Upload and activate"}</button></form><section className="record-list"><div className="form-heading"><div><span className="section-kicker">VERSION HISTORY</span><h2>{loading ? "Loading…" : `${items.length} versions`}</h2></div></div>{loading ? <p className="admin-muted">Loading résumé versions…</p> : items.length === 0 ? <div className="admin-empty"><h3>No résumé uploaded.</h3><p>The public résumé actions will point visitors to Contact until an active PDF is available.</p></div> : items.map((item) => <article className="resume-version" key={item.id}><div className="resume-version-main"><span className="section-kicker">VERSION {String(item.version).padStart(2, "0")}{item.is_active ? " · ACTIVE" : ""}</span>{item.is_active && !item.file_available && <p className="admin-error">The active file is missing from storage. Upload a replacement to restore the public résumé button.</p>}<h3>{item.file_name}</h3><p>Uploaded {new Date(item.uploaded_at).toLocaleString()}</p></div><div className="resume-version-actions"><a className="text-link" href={item.is_active ? "/api/resume" : `/api/admin/resumes/${item.id}/file`} target="_blank" rel="noreferrer">View / download ↗</a>{item.is_active ? <button className="text-button" type="button" disabled={busy} onClick={() => void setActive(item, false)}>Deactivate</button> : <button className="text-button" type="button" disabled={busy} onClick={() => void setActive(item, true)}>Activate</button>}<button className="text-button text-button--danger" type="button" disabled={busy} onClick={() => void remove(item)}>Delete</button></div></article>)}</section></main>;
}








