"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
const links = [{ href: "/projects", label: "Projects" }, { href: "/about", label: "About" }, { href: "/writing", label: "Writing" }, { href: "/contact", label: "Contact" }];
function Mark() { return <svg className="brand-mark" viewBox="0 0 34 34" fill="none" aria-hidden="true"><path d="M7 25 17 7l10 18" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><circle cx="7" cy="25" r="3" fill="var(--accent)"/><circle cx="17" cy="7" r="3" fill="currentColor"/><circle cx="27" cy="25" r="3" fill="var(--accent)"/><path d="M10 25h14" stroke="currentColor" strokeWidth="1.5" strokeDasharray="2 3"/></svg>; }
function ThemeToggle() { function toggle() { const next = document.documentElement.dataset.theme === "dark" ? "light" : "dark"; document.documentElement.dataset.theme = next; try { localStorage.setItem("theme", next); } catch {} }
 return <button className="theme-toggle" type="button" onClick={toggle} aria-label="Toggle color theme" title="Toggle color theme"><svg className="theme-sun" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="3.5" stroke="currentColor" strokeWidth="1.5"/><path d="M10 1.5v2m0 13v2m8.5-8.5h-2m-13 0h-2m14.5-6-1.4 1.4m-9.2 9.2L3 16m13.5 0-1.4-1.4M4.4 4.4 3 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg><svg className="theme-moon" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M16.6 12A7 7 0 0 1 8 3.4 7 7 0 1 0 16.6 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg></button>;
}
export default function SiteHeader({ githubUrl = "https://github.com/Arshanashraf", resumeAvailable = false }: { githubUrl?: string; resumeAvailable?: boolean }) {
 const pathname = usePathname(); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
 useEffect(() => { const update = () => setScrolled(window.scrollY > 8); const frame = window.requestAnimationFrame(update); window.addEventListener("scroll", update, { passive: true }); return () => { window.cancelAnimationFrame(frame); window.removeEventListener("scroll", update); }; }, []);
 useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setMenuOpen(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
 return <header className={`site-header shell${scrolled ? " site-header--scrolled" : ""}`}><Link className="brand" href="/" aria-label="Arshan Ashraf home" onClick={() => setMenuOpen(false)}><Mark/><span>Arshan Ashraf<span className="brand-period">.</span></span></Link><nav className={`main-nav${menuOpen ? " main-nav--open" : ""}`} id="site-navigation" aria-label="Main navigation">{links.map((link) => <Link key={link.href} href={link.href} aria-current={pathname === link.href || (link.href !== "/" && pathname.startsWith(`${link.href}/`)) ? "page" : undefined} onClick={() => setMenuOpen(false)}>{link.label}</Link>)}{resumeAvailable && <a className="mobile-resume-link" href="/api/resume?download=1">Download résumé ↗</a>}</nav><div className="header-actions"><a className="github-link" href={githubUrl} target="_blank" rel="noreferrer">GitHub <span>↗</span></a>{resumeAvailable && <a className="header-resume" href="/api/resume?download=1" download>Résumé ↓</a>}<ThemeToggle/><button className="menu-toggle" type="button" aria-label={menuOpen ? "Close navigation menu" : "Open navigation menu"} aria-expanded={menuOpen} aria-controls="site-navigation" onClick={() => setMenuOpen(!menuOpen)}><span/><span/></button></div></header>;
}


