import {NextResponse} from "next/server";
import {createHash} from "node:crypto";
import {currentAdmin} from "@/lib/auth";
import {database} from "@/lib/database";
import {sameOrigin} from "@/lib/security";
const resources={projects:{table:"projects",fields:["title","slug","summary","context","role_scope","approach","decisions","challenges","outcome","outcome_type","status","is_sample","featured","currently_building","sort_order","repo_url","demo_url","seo_title","seo_description","social_image","published_at","technology_names"],touch:true},skills:{table:"skills",fields:["name","group_name","confidence","description","is_visible","sort_order"],touch:true},experience:{table:"experiences",fields:["organization","role","started_on","ended_on","description","is_visible","sort_order"],touch:true},achievements:{table:"achievements",fields:["title","achieved_on","description","evidence_url","is_visible","sort_order"],touch:true},"blog-posts":{table:"blog_posts",fields:["title","slug","excerpt","body_markdown","cover_image","cover_alt","category","status","seo_title","seo_description","published_at"],touch:true},messages:{table:"messages",fields:["status"],touch:false}} as const;
type Resource=keyof typeof resources;function bad(message:string,status:number){return NextResponse.json({error:message},{status,headers:{"Cache-Control":"no-store"}})}function getConfig(name:string){return Object.hasOwn(resources,name)?resources[name as Resource]:undefined}function validId(id:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)}
function validField(name:Resource,key:string,value:unknown){if(value===null)return true;if(typeof value==="string"){if(value.length>12_000)return false;if(key==="slug"&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value))return false;if(key==="technology_names"&&value.length>800)return false;if(key.endsWith("_url")||key==="repo_url"||key==="demo_url"){try{if(new URL(value).protocol!=="https:")return false}catch{return false}}if(key==="status")return(name==="messages"?["unread","read","archived"]:["draft","published","archived"]).includes(value);if(key==="confidence")return["core","working_knowledge","currently_learning","exploring"].includes(value);if(key==="outcome_type")return["unmeasured","measured","intended"].includes(value);return true}if(typeof value==="boolean")return true;if(typeof value==="number")return Number.isSafeInteger(value)&&Math.abs(value)<=1_000_000;return false}
function parseTechnologies(value:unknown){if(typeof value!=="string")return[];const names=[...new Set(value.split(",").map((name)=>name.trim()).filter(Boolean))];if(names.length>25||names.some((name)=>name.length>80||/[\x00-\x1f]/.test(name)))throw new Error("Invalid technology list.");return names}
async function syncTechnologies(client:import("pg").PoolClient,id:string,names:string[]){await client.query("DELETE FROM project_technologies WHERE project_id=$1",[id]);for(const[index,name]of names.entries()){const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"technology";const suffix=createHash("sha256").update(name.toLowerCase()).digest("hex").slice(0,8);const {rows}=await client.query("INSERT INTO technologies(name,slug) VALUES($1,$2) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id",[name,slug+"-"+suffix]);await client.query("INSERT INTO project_technologies(project_id,technology_id,sort_order) VALUES($1,$2,$3)",[id,rows[0].id,index])}}
export async function PATCH(request:Request,context:RouteContext<"/api/admin/[resource]/[id]">){if(!sameOrigin(request))return bad("This request could not be accepted.",403);const {resource:name,id}=await context.params;const config=getConfig(name);if(!config||!validId(id))return bad("Not found.",404);if(!await currentAdmin())return bad("Authentication required.",401);let input:unknown;try{const raw=await request.text();if(Buffer.byteLength(raw)>20_000)return bad("Request is too large.",413);input=JSON.parse(raw)}catch{return bad("Invalid update.",400)}if(!input||typeof input!=="object"||Array.isArray(input))return bad("Invalid update.",400);const fields=Object.keys(input as object);const record=input as Record<string,unknown>;if(!fields.length||fields.some((field)=>!(config.fields as readonly string[]).includes(field)||!validField(name as Resource,field,record[field])))return bad("Check the fields and try again.",400);let technologies:string[]=[];try{if(name==="projects"&&"technology_names" in record){technologies=parseTechnologies(record.technology_names);delete record.technology_names}}catch{return bad("Check the technology list.",400)}const columns=Object.keys(record);try{const db=database();const client=name==="projects"?await db.connect():null;try{if(client)await client.query("BEGIN");const runner=client??db;const set=columns.map((field,index)=>`${field}=$${index+1}`);if(config.touch)set.push("updated_at=now()");const values=columns.map((field)=>record[field]);values.push(id);const result=await runner.query(`UPDATE ${config.table} SET ${set.join(",")} WHERE id=$${values.length} RETURNING *`,values);if(!result.rowCount)return bad("Record not found.",404);if(client&&"technology_names" in (input as object))await syncTechnologies(client,id,technologies);if(client)await client.query("COMMIT");return NextResponse.json({item:{...result.rows[0],...(name==="projects"?{technology_names:technologies}:{})}},{headers:{"Cache-Control":"no-store"}})}catch(error){if(client)await client.query("ROLLBACK");throw error}finally{client?.release()}}catch{return bad("Could not update the record. Check the field values.",400)}}
export async function DELETE(request:Request,context:RouteContext<"/api/admin/[resource]/[id]">){if(!sameOrigin(request))return bad("This request could not be accepted.",403);const {resource:name,id}=await context.params;const config=getConfig(name);if(!config||!validId(id))return bad("Not found.",404);if(!await currentAdmin())return bad("Authentication required.",401);try{const raw=await request.text();if(Buffer.byteLength(raw)>2048)return bad("Invalid deletion request.",400);const body=JSON.parse(raw) as {confirm?:unknown};if(body?.confirm!==true)return bad("Explicit confirmation is required.",400);const result=await database().query(`DELETE FROM ${config.table} WHERE id=$1`,[id]);return result.rowCount?new NextResponse(null,{status:204,headers:{"Cache-Control":"no-store"}}):bad("Record not found.",404)}catch{return bad("Could not delete the record.",400)}}

