import {NextResponse} from "next/server";
import {createHash} from "node:crypto";
import {currentAdmin} from "@/lib/auth";
import {database} from "@/lib/database";
import {sameOrigin} from "@/lib/security";
const resources={projects:{table:"projects",fields:["title","slug","summary","context","role_scope","approach","decisions","challenges","outcome","outcome_type","status","is_sample","featured","currently_building","sort_order","repo_url","demo_url","seo_title","seo_description","social_image","published_at","technology_names"],required:["title","slug","summary"],order:"sort_order ASC,created_at DESC"},skills:{table:"skills",fields:["name","group_name","confidence","description","is_visible","sort_order"],required:["name","group_name","confidence"],order:"sort_order ASC,name ASC"},experience:{table:"experiences",fields:["organization","role","started_on","ended_on","description","is_visible","sort_order"],required:["organization","role"],order:"sort_order ASC,started_on DESC"},achievements:{table:"achievements",fields:["title","achieved_on","description","evidence_url","is_visible","sort_order"],required:["title"],order:"sort_order ASC,achieved_on DESC"},"blog-posts":{table:"blog_posts",fields:["title","slug","excerpt","body_markdown","cover_image","cover_alt","category","status","seo_title","seo_description","published_at"],required:["title","slug"],order:"published_at DESC,created_at DESC"},messages:{table:"messages",fields:["status"],required:[],order:"received_at DESC"}} as const;
type Resource=keyof typeof resources;
function bad(message:string,status:number){return NextResponse.json({error:message},{status,headers:{"Cache-Control":"no-store"}})}
function configFor(name:string){return Object.hasOwn(resources,name)?resources[name as Resource]:undefined}
function validate(name:Resource,value:unknown,updating=false){if(!value||typeof value!=="object"||Array.isArray(value))return null;const config=resources[name];const input=value as Record<string,unknown>;const fields=Object.keys(input);if(!fields.length||fields.some((field)=>!(config.fields as readonly string[]).includes(field)))return null;for(const [field,item] of Object.entries(input)){if(item===null)continue;if(typeof item==="string"){if(item.length>12_000)return null;if(field==="slug"&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(item))return null;if(field==="technology_names"&&item.length>800)return null;if(field.endsWith("_url")||field==="repo_url"||field==="demo_url"){try{if(new URL(item).protocol!=="https:")return null}catch{return null}}if(field==="status"&&!((name==="messages"?["unread","read","archived"]:["draft","published","archived"]) as readonly string[]).includes(item))return null;if(field==="confidence"&&!(["core","working_knowledge","currently_learning","exploring"] as readonly string[]).includes(item))return null;if(field==="outcome_type"&&!(["unmeasured","measured","intended"] as readonly string[]).includes(item))return null;}else if(typeof item==="number"){if(!Number.isSafeInteger(item)||Math.abs(item)>1_000_000)return null;}else if(typeof item!=="boolean")return null;}if(!updating&&config.required.some((field)=>typeof input[field]!=="string"||!(input[field] as string).trim()))return null;return Object.fromEntries(fields.map((field)=>[field,input[field]]));}
function parseTechnologies(value:unknown){if(typeof value!=="string")return [];const names=[...new Set(value.split(",").map((name)=>name.trim()).filter(Boolean))];if(names.length>25||names.some((name)=>name.length>80||/[\x00-\x1f]/.test(name)))throw new Error("Use up to 25 technology names.");return names;}
async function syncTechnologies(client:import("pg").PoolClient,projectId:string,names:string[]){await client.query("DELETE FROM project_technologies WHERE project_id=$1",[projectId]);for(const [index,name] of names.entries()){const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"technology";const suffix=createHash("sha256").update(name.toLowerCase()).digest("hex").slice(0,8);const result=await client.query("INSERT INTO technologies(name,slug) VALUES($1,$2) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id",[name,slug+"-"+suffix]);await client.query("INSERT INTO project_technologies(project_id,technology_id,sort_order) VALUES($1,$2,$3)",[projectId,result.rows[0].id,index]);}}
export async function GET(_request:Request,context:RouteContext<"/api/admin/[resource]">){const {resource:name}=await context.params;const config=configFor(name);if(!config)return bad("Not found.",404);if(!await currentAdmin())return bad("Authentication required.",401);try{const db=database();if(name==="messages"){const policy=await db.query<{value:unknown}>("SELECT value FROM portfolio_settings WHERE key='privacy_retention_days' LIMIT 1");const days=Number(policy.rows[0]?.value);if(Number.isInteger(days)&&days>=1&&days<=365)await db.query("DELETE FROM messages WHERE received_at < now()-($1::int * interval '1 day')",[days]);}const query=name==="projects"?"SELECT p.*,COALESCE(array_agg(t.name ORDER BY pt.sort_order) FILTER(WHERE t.name IS NOT NULL),'{}') AS technology_names FROM projects p LEFT JOIN project_technologies pt ON pt.project_id=p.id LEFT JOIN technologies t ON t.id=pt.technology_id GROUP BY p.id ORDER BY p.sort_order ASC,p.created_at DESC LIMIT 200":"SELECT * FROM "+config.table+" ORDER BY "+config.order+" LIMIT 200";const {rows}=await db.query(query);return NextResponse.json({items:rows},{headers:{"Cache-Control":"no-store"}})}catch{return bad("Could not load records.",503)}}
export async function POST(request:Request,context:RouteContext<"/api/admin/[resource]">){if(!sameOrigin(request))return bad("This request could not be accepted.",403);const {resource:name}=await context.params;const config=configFor(name);if(!config)return bad("Not found.",404);if(name==="messages")return bad("Messages are received through the contact form.",405);if(!await currentAdmin())return bad("Authentication required.",401);let payload:unknown;try{const raw=await request.text();if(Buffer.byteLength(raw)>20_000)return bad("Request is too large.",413);payload=JSON.parse(raw)}catch{return bad("Invalid record.",400)}const fields=validate(name as Resource,payload);if(!fields)return bad("Check the fields and try again.",400);const input=fields as Record<string,unknown>;let technologies:string[]=[];try{if(name==="projects")technologies=parseTechnologies(input.technology_names);delete input.technology_names}catch{return bad("Check the technology list.",400)}const columns=Object.keys(input);try{const db=database();const client=name==="projects"?await db.connect():null;try{if(client)await client.query("BEGIN");const runner=client??db;const values=columns.map((field)=>input[field]);const placeholders=columns.map((_,index)=>`$${index+1}`).join(",");const result=await runner.query(`INSERT INTO ${config.table}(${columns.join(",")}) VALUES(${placeholders}) RETURNING *`,values);if(client)await syncTechnologies(client,String(result.rows[0].id),technologies);if(client)await client.query("COMMIT");return NextResponse.json({item:{...result.rows[0],...(name==="projects"?{technology_names:technologies}: {})}},{status:201,headers:{"Cache-Control":"no-store"}})}catch(error){if(client)await client.query("ROLLBACK");throw error}finally{client?.release()}}catch{return bad("Could not save the record. Check required fields and unique slugs.",400)}}

