import Link from "next/link";
import { database } from "@/lib/database";
const cards = [["projects", "Projects", "/admin/projects"], ["skills", "Skills", "/admin/skills"], ["experiences", "Experience", "/admin/experience"], ["achievements", "Achievements", "/admin/achievements"], ["blog_posts", "Blog posts", "/admin/blog-posts"], ["messages", "Messages", "/admin/messages"], ["resumes", "Résumé versions", "/admin/resume"]] as const;
export default async function AdminOverview() {
  const pool = database();
  const totals = await Promise.all(cards.map(async ([table]) => { const { rows } = await pool.query<{ count: string }>("SELECT count(*)::text AS count FROM " + table); return rows[0]?.count ?? "0"; }));
  const { rows: recent } = await pool.query<{ kind: string; label: string; updated_at: Date }>("SELECT kind,label,updated_at FROM (SELECT 'Project' AS kind,title AS label,updated_at FROM projects UNION ALL SELECT 'Skill',name,updated_at FROM skills UNION ALL SELECT 'Experience',role || ' · ' || organization,updated_at FROM experiences UNION ALL SELECT 'Achievement',title,updated_at FROM achievements UNION ALL SELECT 'Article',title,updated_at FROM blog_posts UNION ALL SELECT 'Résumé',file_name,uploaded_at FROM resumes) AS recent_content ORDER BY updated_at DESC LIMIT 5");
  return <div className="dashboard-overview"><div className="manager-title"><div><span className="section-kicker">PRIVATE WORKSPACE</span><h1>Overview</h1></div><Link className="button button--quiet" href="/">View public site ↗</Link></div><p className="admin-note">Your actual content at a glance. Drafts stay private until you publish them.</p><div className="overview-cards">{cards.map((card, index) => <Link className="overview-card" href={card[2]} key={card[0]}><span className="section-kicker">{card[1]}</span><strong>{totals[index]}</strong><span>Manage {card[1].toLowerCase()} ↗</span></Link>)}</div><section className="admin-guide"><div><span className="section-kicker">RECENTLY UPDATED</span><h2>Latest content changes</h2></div>{recent.length ? <ul className="admin-recent-list">{recent.map((item, index) => <li key={`${item.kind}-${item.label}-${index}`}><span>{item.kind}</span><b>{item.label}</b><time dateTime={new Date(item.updated_at).toISOString()}>{new Date(item.updated_at).toLocaleDateString()}</time></li>)}</ul> : <p className="admin-muted">New updates will appear here as you add portfolio content.</p>}</section><section className="admin-guide"><span className="section-kicker">BEFORE PUBLISHING</span><h2>Review the facts first.</h2><p>Replace sample project details with your verified role, decisions, timeline, outcomes, and project links. Add a confidence label to each skill yourself.</p></section></div>;
}
